In [98]:
from sklearn import preprocessing
import numpy as np
import pandas as pd

In [99]:
DF = pd.read_csv('../data/js_viz_Data.csv')
DF.drop('index', axis=1, inplace=True)

In [89]:
nanDF = DF[pd.isnull(DF).any(axis=1)]

In [90]:
DF.dropna(axis=0, how='any', thresh=None, subset=None, inplace=True)

In [74]:
DF

,Unnamed: 0,package,github_repo,tags,search_terms,forks,stars,so_tag_counts,so_questions_counts,downloads,dl_growth_rates
0,0,plottable,palantir/plottable,[plottable.js;plottable],[plottable;plottablejs],181,2170,55,94706,36553,0.486324
1,1,taucharts,TargetProcess/tauCharts,[taucharts; taucharts.js],[taucharts;tauchartsjs],88,1361,0,4,20583,0.273709
2,2,metrics-graphics,mozilla/metrics-graphics,[metricsgraphicsjs],[metrics-graphics;metricsgraphicsjs],437,6694,13,159,11845,0.041618
3,3,dc,dc-js/dc.js,[dc.js],[dcjs;dc.js;dc-js],1551,5775,1196,1846,65422,-0.002206
4,4,smoothie,joewalnes/smoothie,[smoothie.js],[smoothie-charts;smoothie.js;smoothiejs],156,1646,9,28,4769,0.035249
5,5,keen-dataviz,keen/keen-dataviz.js,[keen-dataviz.js;keen-dataviz],[keen-dataviz],29,118,0,0,10495,-0.037949
6,6,chartist,gionkunz/chartist-js,[chartist.js],[chartist;chartistjs],1808,9744,130,186,243584,0.061352
7,7,highcharts,highcharts/highcharts,[highcharts],[highcharts;highchartsjs],2016,6526,16592,16502,1425832,0.104917
8,8,n3-charts,n3-charts/line-chart,[n3-charts],[n3-charts;n3-line-chart],200,1217,11,46,13330,-0.065470
9,9,leaflet,Leaflet/Leaflet,[leaflet],[leaflet],3248,19106,5770,5770,1007700,0.091290
10,10,deck.gl,uber/deck.gl,[deck.gl],[deck.gl],380,3311,6,6,57605,0.205972
11,11,amcharts,ChimpStudios/AmCharts,[amcharts],[amcharts],33,110,1176,1176,4573,0.074939
12,12,cytoscape,cytoscape/cytoscape.js,[cytoscape.js;cytoscape],[cytoscape;cytoscapejs],506,3362,721,474,64635,0.033230
13,13,chart.js,chartjs/Chart.js,[chart.js],[chartjs;chart.js],7993,31580,3185,6102,2259748,0.051097
14,14,morris.js,morrisjs/morris.js,[morris.js],[morris-charts;morrisjs;morris.js],1144,6589,454,1018,47247,0.080752
15,15,jsxgraph,jsxgraph/jsxgraph,[jsxgraph],[jsxgraph],86,334,32,32,164,0.075776
16,16,pizza pie charts,zurb/pizza,[pizza-pie-charts],[pizza-pie-charts],65,423,0,0,82,0.019824
17,17,jquery-sparkline,gwatts/jquery.sparkline,[sparklines],[jquery-sparkline;jquery-sparklines],251,1071,141,281,71805,0.148199
18,18,chartkick,ankane/chartkick,[chartkick],[chartkick;chartkickjs],437,4398,205,314,16667,0.161966
19,19,zingchart,zingchart/ZingChart,[zingchart],[zingchart],27,146,195,195,10203,0.106328
20,20,anychart,AnyChart/AnyChart,[anychart],[anychart;anychartjs],14,127,86,102,6554,0.319863
21,21,dojo charting,johntexastechsmith/DojoTrendCharting,[dojox.charting],[dojo-charting;dojox-charting;dojochart;dojox-...,0,0,186,555,189350,-0.000459
22,22,d3,d3/d3,[d3.js],[d3;d3js],17486,66903,26885,37654,5022889,0.040359
23,23,vizceral,Netflix/vizceral,[vizceral],[vizceral],134,1543,0,0,10270,-0.117836
24,24,envision,HumbleSoftware/envisionjs,[envision.js],[envision.js],257,1565,1,1,286,-0.035104
25,25,jenscript,sjanaud/jenscript,[jenscript],[jenscript],0,13,0,0,1278,-0.001535
26,26,ejscharts,EmpriseCorporation/EJSCharts,[ejs-chart],[ejs-chart;ejscharts],19,23,2,27,188,NaN
27,27,cubism,square/cubism,[cubism.js],[cubism.js;cubism],541,4553,92,147,2133,-0.057777
28,28,flot,flot/flot,[flot],[flot;flotjs],1412,5412,2016,2543,34492,0.131369
29,29,flotr2,HumbleSoftware/Flotr2,[flotr2],[flotr2],535,2414,32,32,439,0.463450
30,30,echarts,ecomfe/echarts,[echarts],[echarts;echartsjs],6132,19732,96,148,179641,0.210272
31,31,jqplot,jqPlot/jqPlot,[jqplot],[jqplot],70,147,1689,1689,538,0.211074
32,32,uvcharts,Imaginea/uvCharts,[uvcharts],[uvcharts],76,228,1,1,47,0.057681
33,33,xcharts,tenXer/xcharts,[xcharts],[xcharts],194,1793,10,10,526,0.093357
34,34,plotly.js,plotly/plotly.js,[plotly],[plotly;plotlyjs],704,6661,1963,94877,188821,0.034746
35,35,dygraphs,danvk/dygraphs,[dygraphs],[dygraphs],491,2221,745,745,40067,0.078817
36,36,nvd3,novus/nvd3,[nvd3.js],[nvd3;nvd3js],2072,6100,1768,2009,422159,0.015147
37,37,fusioncharts,fusioncharts/fusionmaps-dist,[fusioncharts],[fusioncharts],1,0,606,606,8196,0.168625
38,38,c3,vace/c3.js,[c3.js;c3],[c3;c3js],2,8,872,17706,432160,0.040732
39,39,webcharts,RhoInc/Webcharts,[webcharts],[webcharts],1,13,0,0,706,-0.060980
40,40,victory,FormidableLabs/victory,[victory-charts],[victory-charts],139,4675,5,5,159738,0.068592
41,41,sigma,jacomyal/sigma.js,[sigma.js],[sigma-js;sigmajs],1169,7393,158,104,4979,0.090936
42,42,cesium,AnalyticalGraphicsInc/cesium,[cesium],[cesium;cesiumjs],1135,2362,394,460,37328,0.070375
43,43,graphael,jjacobson93/graphael,[graphael],[graphael;graphaeljs],2,16,186,123,2329,0.565591
44,44,ember-charts,Addepar/ember-charts,[ember-charts],[ember-charts;embercharts],126,768,4,93,10356,0.192504
45,45,modestmaps,stamen/modestmaps-js,[modestmaps.js],[modestmap;modestmapsjs],161,566,0,10,10237,-0.223165
46,46,rickshaw,shutterstock/rickshaw,[rickshaw],[rickshaw;rickshawjs],952,6076,184,235,30494,-0.014671

In [100]:
DF_pre_scaled = DF[['forks', 'stars','so_tag_counts','so_questions_counts','downloads','dl_growth_rates']]

In [101]:
DF_scaled = pd.DataFrame(preprocessing.scale(DF_pre_scaled), columns=DF_pre_scaled.columns)

In [102]:
DF_scaled['overall_score'] = DF_scaled.sum(axis=1)
DF_scaled['package'] = DF['package']

In [94]:
DF_scaled = DF_scaled.append(nanDF[['package', 'forks', 'stars','so_tag_counts','so_questions_counts','downloads','dl_growth_rates']])

In [110]:
DF_scaled.sort_values(['overall_score'], axis=0, ascending=False, inplace=True, na_position='last')

In [111]:
DF_scaled.head()

,forks,stars,so_tag_counts,so_questions_counts,downloads,dl_growth_rates,overall_score,package
22,5.756790,5.692063,5.620210,1.597244,5.883563,-0.349363,24.200507,d3
13,2.409675,2.430622,0.384589,-0.002085,2.471051,-0.275655,7.418198,chart.js
0,-0.344741,-0.284860,-0.306866,4.489134,-0.274621,2.712016,5.990063,plottable
7,0.302258,0.117338,3.346360,0.525077,1.441155,0.093801,5.825989,highcharts
34,-0.160337,0.129803,0.114635,4.497802,-0.086568,-0.387901,4.107433,plotly.js

In [115]:
final_DF = pd.DataFrame(columns=['Package', 'Rank', 'Overall', 'Github', 'Stack Overflow', 'Downloads'])

In [127]:
final_DF['Package'] = DF_scaled['package']
final_DF['Github'] = DF_scaled[['forks', 'stars']].mean(axis=1)
final_DF['Stack Overflow'] = DF_scaled[['so_tag_counts', 'so_questions_counts']].mean(axis=1)
final_DF['Downloads'] = DF_scaled[['downloads','dl_growth_rates']].mean(axis=1)
final_DF['Overall'] = final_DF[['Github','Stack Overflow','Downloads']].sum(axis=1)
final_DF['Rank'] = final_DF['Overall'].rank(ascending=0).astype(int)

In [131]:
final_DF.style.set_table_styles([
    {'selector': '.row_heading, .blank', 'props': [('display', 'none;')]}
])

In [133]:
final_DF.to_csv('../output/js_viz_final_Rankings.csv', index = False)